### ISSUE TITLE
Add front_default sprites for gen9

### ISSUE THREAD

**Issue by diduseetheocean** [PokeAPI/sprites#101]
The front_default sprites are currently missing for pokemon of the 9 generation.

Acceptance criteria:
- sprites should match the current style of the already existing ones (b/w)
- size should be in 96x96 pixel
- fileformat .png

**Comment by diduseetheocean** [comment]
Trying to contact following artist to ask for usage permission of his sprites:
https://www.deviantart.com/kingofthe-x-roads/art/Gen-9-Sprites-Pokemon-Scarlet-and-Violet-908341834

**Comment by Naramsim** [comment]
isn't there an official version for those sprites?

**Comment by diduseetheocean** [comment]
Didn't found one.
Here at the bottom it says that since pkmn #650 the sprites were taken from smogon. So i think there are no official sprites released after that and they are all fanart, but iam not sure.

(scroll to the bottom of this link)
https://github.com/PokeAPI/sprites

**Comment by diduseetheocean** [comment]
Also found this source:
https://dex.pokemonshowdown.com/pokemon/

But the sprites of the 9th generation in the list have a totally different style.

**Comment by Naramsim** [comment]
oh yes, now I remember. It would be cool to have the Smogon ones. But if that artist agrees to supply us with his ones we could expose those

**Comment by diduseetheocean** [comment]
> oh yes, now I remember. It would be cool to have the Smogon ones. But if that artist agrees to supply us with his ones we could expose those

I think the artist is one of many artists who makes also the sprites for smogon. His name appears in the readme and the google-sheet.

**Comment by Naramsim** [comment]
Yeah! We are completely no profit. To be honest we use our money to provide our service. 

Does the guy have a GitHub account?

If we integrate his images, a separate credit line should be added to our readme, imho.

**Comment by diduseetheocean** [comment]
Couldn't find any github page of him. No link in any of his profiles either. Think he is a pure artist. But linking
https://www.deviantart.com/kingofthe-x-roads or https://twitter.com/kingofthexroad5
could be done.
