### ISSUE TITLE
Missmatch between JSON sprites and actual available (hosted) sprites

### ISSUE THREAD

**Issue by arturomoncadatorres** [PokeAPI/sprites#11]
I am fetching some sprites using the API. When I make the request, the response JSON shows that the sprites are unavailable. For example, for Zeraora (number 807):

![image](https://user-images.githubusercontent.com/37126116/61893112-9c1b9600-af0d-11e9-9086-534396f69f61.png)

However, if [I look "manually"](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/807.png), there is a sprite corresponding to that Pokemon. Could there be a mismatch between the JSON response and the actual available (hosted) sprites?

**Comment by arturomoncadatorres** [comment]
Would it be possible that it has something to do [with this commit](https://github.com/PokeAPI/sprites/commit/328d40ef96f5fd811a9bb3877f77cfbfda3d0fb3)?

**Comment by Naramsim** [comment]
Closing since the API was synced.
