### ISSUE TITLE
Chesnaught back and back shiny sprites missing

### ISSUE THREAD

**Issue by saverioscagnoli** [PokeAPI/sprites#121]
Hello, it seems that the back_default and back_shiny for Chesnaught (#652) are missing.
Thank you!

**Comment by Naramsim** [comment]
Hi, Can you contribute and add them?

**Comment by saverioscagnoli** [comment]
Yes, gladly! I will them and others i noticed were missing. Sorry it was not immediate but it is my first issue, and I'm trying to understand how it works, thank you for your project!
