### ISSUE TITLE
Add type name icons

### ISSUE THREAD

**Issue by gabeklavans** [PokeAPI/sprites#137]
I would love to be able to use PokeAPI to fetch the type name icon sprites from a specific generation.

They could be returned as a property of a [type object](https://pokeapi.co/docs/v2#types).

The most succinct list I can find of them right now is on [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Type#Name_icons).

**Comment by FallenDeity** [comment]
Hmm we could have it under type object as 
```json
"icons": {
    "generation-i": {
          "game": {
               "symbol": "",
               "name_icon": ""
            }
      }
}
 ```
 Maybe something for a tera type too ig

**Comment by Naramsim** [comment]
I'd use _sprites_ instead of _icons_

**Comment by gabe-yobe** [comment]
I can dump the sprites here in the meantime, if that would help. Where would they go

**Comment by gabeklavans** [comment]
I can dump the sprites here in the meantime, if that would help

**Comment by Naramsim** [comment]
I'd put them here: https://github.com/PokeAPI/sprites/tree/master/sprites in a new folder `types`

**Comment by FallenDeity** [comment]
Yeah sure u can zip them up and dump it helps if u categorise it folder wise too for certain types or games, upto you

**Comment by gabeklavans** [comment]
> if u categorise it folder wise too for certain types or games, upto you

I'm thinking I'll categorize by game, matching how bulbapedia does it

**Comment by gabeklavans** [comment]
Moving tracking for this over to https://github.com/PokeAPI/pokeapi/issues/1066
