### ISSUE TITLE
[sprites/pokemon/shiny/678.png] incorrect sprite

### ISSUE THREAD

**Issue by acxz** [PokeAPI/sprites#142]
This image should be the shiny of this: https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/678.png

But rather it is incorrectly the shiny of the female: https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/678.png

**Comment by Naramsim** [comment]
Hi!, could you fix it?

**Comment by acxz** [comment]
Yep on it, I found the Smogon sprite for meowstic here:

https://www.smogon.com/forums/threads/x-y-sprite-project.3486712/

https://docs.google.com/spreadsheets/d/1Gn0UORn-unvcbUeQhQdEBz0ADNcH49BZZqQ1dpXm9eo/edit#gid=0
