### ISSUE TITLE
Game characters data

### ISSUE THREAD

**Issue by Sylux6** [PokeAPI/sprites#15]
Just a suggestion to know if adding data/sprites about game characters and trainers can be a thing ?

**Comment by Naramsim** [comment]
It can be sure a thing. Keep in mind that right now the API doesn't serve any data about characters and trainers. So it's not only a matter of adding pictures here but also implement the logic and the structure of a possible `/character/{character}` endpoint.

**Comment by Sylux6** [comment]
Sure, it's a huge work.

**Comment by Naramsim** [comment]
Closing since it's too broad and we won't have time to add trainers and characters to the API.
