### ISSUE TITLE
Thumbnail Sprites

### ISSUE THREAD

**Issue by brandonhorst** [PokeAPI/sprites#28]
From what I can tell, it's not currently possible to grab the thumbnail/mini/small versions of sprites that are used on the Pokemon Select screen. [These sprites](https://img.pokemondb.net/sprites/x-y/montage-icon-1310b.png)

Do you have any plans to add these to the API? Would you except a PR?

**Comment by Naramsim** [comment]
Transferring the issue. 

We could use https://github.com/msikma/pokesprite since all the images are actually copyrighted by Nintendo.

**Comment by C-Garza** [comment]
So do we want to grab the `gen-7` pokemon sprites from that repo to here? And if so, how do we want to structure it in the sprites repo? 

Since they're gen-7 they could go in the `versions/generation-vii/` folder as something like `box-sprites` since the `gen-8` box sprites are a bit different.

**Comment by Naramsim** [comment]
Could be. Instead of `box-sprites` I was thinking `icons`. This is how Veekun calls them: https://veekun.com/dex/media/pokemon/icons/

Anyway, both gen-vii and gen-viii.

**Comment by C-Garza** [comment]
Oh, I didn't realize Veekun had them as well. I'll get the Veekun icons for `gen-vii` then since they use the original 40x30 size and I'll use the repo you mentioned for the `gen-viii` icons.
