### ISSUE TITLE
Are these images free to you in an application for personal use ?

### ISSUE THREAD

**Issue by ritesh-malav** [PokeAPI/sprites#38]
Are these images free to you in an application for personal use ?

**Comment by Naramsim** [comment]
This repository merely collects pictures and sprites for Pokemon and items present in various Nintendo games. 

The copyright of the images belongs to Nintendo and we licensed our repository with a CCv1 license.

https://github.com/PokeAPI/sprites/blob/master/LICENCE.txt

Keep in mind that the images present in this repository are extracted by the ROM cartridges themselves and are not modified in any way.

**Comment by ritesh-malav** [comment]
Since I plan to use these images directly in my personal app so you think it might cause issues ?

**Comment by Naramsim** [comment]
I don't see any issues as long you mention that images' properties are Nintendo's. 

Keep in mind that if you try to upload an app on the Play Store or the App Store, and copyrighted images are found, you will be blocked and your app won't be published.

**Comment by ritesh-malav** [comment]
@Naramsim I am using these images on following website http://mathcharger.com please advice me if I give nintendo credits do you think I will be out of trouble ?

**Comment by Naramsim** [comment]
I cannot advise you, but looking at the website I don't see any mention that the images are property on Nintendo.

**Comment by ritesh-malav** [comment]
I will do that. I just wanted your advice if that if good enough.

**Comment by cgbsu** [comment]
> 
> 
> This repository merely collects pictures and sprites for Pokemon and items present in various Nintendo games.
> 
> The copyright of the images belongs to Nintendo and we licensed our repository with a CCv1 license.
> 
> https://github.com/PokeAPI/sprites/blob/master/LICENCE.txt
> 
> Keep in mind that the images present in this repository are extracted by the ROM cartridges themselves and are not modified in any way.

I don't quite understand how you put it under another license, doesn't Nintendo have their own license?

**Comment by Naramsim** [comment]
To simply put, our license says two things:

1. All image contents within are Copyright The Pokémon Company.
2. This repository is released under CC0.

We are not re-licensing any image here.
