### ISSUE TITLE
Are these hosted anywhere?

### ISSUE THREAD

**Issue by justingolden21** [PokeAPI/sprites#41]
Ideally, I'd like to load them on a webpage only when necessary, without including every file in my repo.

I was hoping to find them at a link like:

https://pokeapi.co/sprites/sprites/pokemon/other/dream-world/1.svg

Or a link to `image` or `sprite` in the json in the API:

https://pokeapi.co/api/v2/pokemon-species/1

But no dice. I'm trying to get a link to the "dream world" pokemon sprites found in `sprites\pokemon\other\dream-world`

Thanks in advance for any help or suggestions. Awesome API : )

**Comment by Naramsim** [comment]
The sprites are hosted here on Github 😄 

If you query a pokemon you can find the links to its pics. https://pokeapi.co/api/v2/pokemon/pikachu and then in the `sprites` property.

The pattern is pretty easy and it follows this repo's structure.

![pika](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/emerald/25.png)

**Comment by phalt** [comment]
The API will provide URI links when you query them, thanks to the magic of hypermedia :star:

**Comment by justingolden21** [comment]
Ah, got it. Thank you.

https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/25.svg (and others)

Is what I was looking for specifically.

**Comment by justingolden21** [comment]
Is there any plan to get the `dream-world` sprites for gens 6+ ?

**Comment by Naramsim** [comment]
I noticed that up to gen5 `dream-world` sprites are SVGs, then gen-6 and gen-7 are PNGs.

I'd like to add to the API the SVG version, if possible.

**Comment by justingolden21** [comment]
Yeah that would be awesome if all dream world sprites for all gens were available as SVG : )
