### ISSUE TITLE
How to use this in a nodejs application?

### ISSUE THREAD

**Issue by mylogon341** [PokeAPI/sprites#45]
Daft question, I'm sure, but I'm trying to use this in a NodeJS application (in TypeScript), but it's just flaking out.
I'm importing with 
```typescript
import sprites from 'pokemon-sprites'
```
but when I run I get the error 
```
Uncaught Error: Cannot find module '/Users/luke/pokeapi/node_modules/pokemon-sprites/index.js'. Please verify that the package.json has a valid "main" entry
```
which makes sense as the `package.json`mentions the `index.js` file, which doesn't actually exist.
Am I just being thick here and need to import it in a different way.

Also, if I get a path from `pokeapi.co` such as `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png`, how might I go about converting that into a request to this repo to grab the right image?
Thanks.
Luke

**Comment by mylogon341** [comment]
I ended up just splitting the url and using path to resolve the local path. Like so

```typescript
String.prototype.imageUrlToPath = function() {
    return this.split("https://raw.githubusercontent.com/PokeAPI/sprites/master")[1]
}
```

then doing
```typescript
import { resolve } from "path"

const path = poke.base.official_artwork.imageUrlToPath()
return resolve
```
kind of rough and ready, but seems to work. If anyone knows a better way, I'd be glad to hear it!

**Comment by Naramsim** [comment]
Hi, this is not a JS module. You cannot import it. 

You can reference the images stored locally when you `npm install` it, though.
