### ISSUE TITLE
How about adding the Pokémon home style images?

### ISSUE THREAD

**Issue by WOTstorm** [PokeAPI/sprites#54]
Hi,

What would you think of adding the Pokémon Home style images? I think I have them all ([source](https://www.spriters-resource.com/nintendo_switch/pokemonhome/)).

I propose to place them in the `dir` named other: https://github.com/PokeAPI/sprites/tree/master/sprites/pokemon/other

With the following structure:
-- home
---- 001.png
---- female
------ 001.png
---- shiny
------ 001.png

The images are 512 x 512 px.
I also have icons  (112 x 112 px), but those are just smaller versions of the images.

Naming the images correctly will take some time on my part, but I can create pull requests in batches.
Let me know what you think.

**Comment by Naramsim** [comment]
Sure we can! If you are able to contribute, that would be awesome. 

I'd name the images without the leading `0`.

**Comment by WOTstorm** [comment]
Also added Gen 7 & 8: https://github.com/PokeAPI/sprites/pull/58
So this issue can be closed after it has been merged :).
