### ISSUE TITLE
Project Pokemon Sprite Index

### ISSUE THREAD

**Issue by HRKings** [PokeAPI/sprites#59]
Would be possible to used the animated sprites from [Project Pokemon Sprite Index](https://projectpokemon.org/home/docs/spriteindex_148) ? The 3D model GIFs are really good.
I was working on a [project](https://github.com/HRKings/projectpokemon-pokeapi-sprites) that maps the named sprites to the PokeAPI IDs, so we could use them.

**Comment by DevMike123** [comment]
Hope your query is resolved? If not, you can reopen it anytime.
