### ISSUE TITLE
Cannot find Gen 8 models

### ISSUE THREAD

**Issue by GregLyons** [PokeAPI/sprites#62]
Hello,

I've cloned this repo to use for a project, and I cannot find the models for the Gen 8 Pokemon. I have looked in sprites/pokemon/versions/generation-viii/, but that only contains icons. I have also looked in the folder sprites/pokemon/, but the images of the Gen 8 Pokemon therein are mostly sprites, rather than models. 

I like the sprites, so I could consider using those instead, but I was wondering if the Gen 8 models are meant to be in this repo or not.

**Comment by Naramsim** [comment]
We currently don't have them

**Comment by GregLyons** [comment]
Understood, thank you!
