### ISSUE TITLE
Bad official artwork for male Indeedee

### ISSUE THREAD

**Issue by simonorono** [PokeAPI/sprites#63]
The official artwork for male and female Indeedee is the same:

https://github.com/PokeAPI/sprites/blob/master/sprites/pokemon/other/official-artwork/876.png
https://github.com/PokeAPI/sprites/blob/master/sprites/pokemon/other/official-artwork/10180.png

The correct one for the male one should be this one: https://assets.pokemon.com/assets/cms2/img/pokedex/full/876.png

**Comment by Naramsim** [comment]
Thanks a lot! @simonorono
