### ISSUE TITLE
Some images in the "model" folder are just the sprites

### ISSUE THREAD

**Issue by swimmath27** [PokeAPI/sprites#7]
I'm not sure if some of the model images were harder to obtain, or if it's a bug or intentional, but some of the model icons are just the sprites again (one such example is treeko, 252.png)

**Comment by Naramsim** [comment]
Yep, you are right, I'm not sure why there was created a model folder...

**Comment by swimmath27** [comment]
I think the models actually look better, so there is some point for the model folder. Also, it's not that every single one is just the sprite, it's just a select few.
Do you know where the models images came from? For the most part, they look like the first frame in the gifs shown on smogon (ie. http://www.smogon.com/dex/xy/pokemon/sableye/, which shows the gif: http://www.smogon.com/dex/media/sprites/xy/sableye.gif), but I'm not sure where smogon got their gifs from either.

I'd be willing to help collect these images if it's not too difficult to obtain them.

**Comment by Naramsim** [comment]
I think we got all our images from Veekun

**Comment by Naramsim** [comment]
I'm tempted to close this issue and remove entirely the `models` folders since it's not used. But maybe we can find out where those images are taken from. Are you willing to investigate a bit @swimmath27?

**Comment by DevMike123** [comment]
Hope your query is resolved? If not, you can reopen it anytime.
