### ISSUE TITLE
how can I fix Icon 

### ISSUE THREAD

**Issue by karim901** [PokeAPI/sprites#71]
![Screenshot_20220720-003643~2](https://user-images.githubusercontent.com/97407628/179863722-a3db897a-3ec5-4327-aa4d-67002e85d59e.png)
![Screenshot_20220720-003643~2](https://user-images.githubusercontent.com/97407628/179863866-eedbc6a3-2526-4672-9326-5b51d4e4c2b6.png)

**Comment by karim901** [comment]
am traying to fix the problem but I don't know where is come from

**Comment by Naramsim** [comment]
Hi, the problem lies within your code. We cannot help you here. Try posting your code HTML+CSS on Stackoverlow

**Comment by DevMike123** [comment]
Assets cannot be recognised.

Try to search the solution over Stackoverflow
