### ISSUE TITLE
Duplicated Sprites

### ISSUE THREAD

**Issue by isikbattenstein** [PokeAPI/sprites#73]
Hello there. :)
What's the reason for having (nearly) duplicated Sprites in this project? 
e.g.:
We got `sprites/sprites/pokemon/model/1.png` with 120x120 32-bit color 
![image](https://user-images.githubusercontent.com/44429590/183508480-01f64143-ab49-40cc-9c38-8d577c7a5300.png)
(I croped this one only to important content)

and `sprites/sprites/pokemon/versions/generation-vi/x-y/1.png` with 43x48 8-bit color
![image](https://user-images.githubusercontent.com/44429590/183508421-a41c9b99-9353-44a6-9d8d-2ef46dffb608.png)

with really minor changes

In folder `sprites/sprites/pokemon/model/` there are still 3 pokemon missing from Gen 6(719 - 721) and every pokemon after Gen 6. So I don't understand the use of this certain folder. 

We also have duplicated sprites with `sprites/sprites/pokemon/*.png` and `sprites/sprites/pokemon/versions/generation-v/black-white/*.png`. Here I can see that there are sprites for all future pokemon after Gen 5. So I do understand that here is a benefit.

**Comment by Naramsim** [comment]
There's no benefit. We should get rid of the `models` folder
