### ISSUE TITLE
Shiny sprites of official artwork is missing.

### ISSUE THREAD

**Issue by DevMike123** [PokeAPI/sprites#78]
@Naramsim I just noticed that there is no folder for the shiny sprites of official artwork.

If there's one, please let me know else add the help wanted label as I am working on it and also need others cooperation.

Thank You:)

**Comment by DevMike123** [comment]
> @Naramsim I just noticed that there is no folder for the shiny sprites of official artwork.
> 
> If there's one, please let me know else add the help wanted label as I am working on it and also need others cooperation.
> 
> Thank You:)

@Naramsim pls reply

**Comment by Naramsim** [comment]
Hi @DevMike123 , are the sprites available somewhere to be downloaded?

**Comment by DevMike123** [comment]
> Hi @DevMike123 , are the sprites available somewhere to be downloaded? 

https://github.com/DecMike123/data

**Comment by Naramsim** [comment]
Feel free to open a PR :)

**Comment by DevMike123** [comment]
> Feel free to open a PR :)

@Naramsim these sprites had been made by me for my personal project. 

So, I have added a note mentioning me as the spriter of these custom sprites :)

Can you please check it:

https://github.com/PokeAPI/sprites/commit/28de2e6382a54a54a75e936ae1cb8f05d02d9644

**Comment by Naramsim** [comment]
Ahh, I thought they were official sprites!

**Comment by Naramsim** [comment]
Of course you should cite yourself! :) And thank you!

**Comment by DevMike123** [comment]
> Of course you should cite yourself! :) And thank you!
> 

Welcome

**Comment by DevMike123** [comment]
@Naramsim I have made 4 prs. Can you merge them?

Due to upload bug, the commits are appearing twice but it will not affect.

Thank you

**Comment by DevMike123** [comment]
> @Naramsim I have made 4 prs. Can you merge them?
> 
> Due to upload bug, the commits are appearing twice but it will not affect.
> 
> Thank you 

I have checked the prs. It's ok.

Due to branch selection problem, it happened, it will work and will not affect you.

Thanks for considering

**Comment by DevMike123** [comment]
> @Naramsim I have made 4 prs. Can you merge them?
> 
> Due to upload bug, the commits are appearing twice but it will not affect.
> 
> Thank you 

Here are the prs:
#80 , #81 , #82 , #83

**Comment by DevMike123** [comment]
> > @Naramsim I have made 4 prs. Can you merge them?
> > 
> > Due to upload bug, the commits are appearing twice but it will not affect.
> > 
> > Thank you 
> 
> Here are the prs:
> #80 , #81 , #82 , #83

@Naramsim pls review them.
