### ISSUE TITLE
arceus-rock in Home sprites

### ISSUE THREAD

**Issue by MxFlix** [PokeAPI/sprites#85]
In the folder of Home sprites, as well as its shiny variant, Arceus Rock variant is listed as stone, instead:
https://github.com/PokeAPI/sprites/blob/master/sprites/pokemon/other/home/493-stone.png
https://github.com/PokeAPI/sprites/blob/master/sprites/pokemon/other/home/shiny/493-stone.png

**Comment by C-Garza** [comment]
Looks like this was resolved in PR #86.
