### ISSUE TITLE
Missing sprites?

### ISSUE THREAD

**Issue by martinohanlon** [PokeAPI/sprites#9]
I have been using pokebase to pull random pokemon from the API and I have noticed that not all pokemon return a sprite.

The following URL returns a `404` - is this a missing sprite or is pokebase looking in the wrong place?

[https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10130.png](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10130.png)

**Comment by Naramsim** [comment]
Hi, 10XXX are IDs for MEGA Pokemons.

If you manually query Mega-Gyarados https://pokeapi.co/api/v2/pokemon/10130/ you see that no sprites are provided (no official ones are present in this repo)

So I think that pokebase is just guessing that the sprite for Mega-Gyarados is present at that URL
