### ISSUE TITLE
Using the installed npm library in node_modules on deployment

### ISSUE THREAD

**Issue by FluffaTheDuck** [PokeAPI/sprites#90]
I have the library installed with npm and it gets installed in node_modules, how do I make it so when i deploy it with vite i can still use those images, I'm using react ?

**Comment by Naramsim** [comment]
Hi, I'm not sure how you would use it in Vite or React. In a way, you need to tell your framework to load/point to the images in that specific folder.

**Comment by DevMike123** [comment]
> I have the library installed with npm and it gets installed in node_modules, how do I make it so when i deploy it with vite i can still use those images, I'm using react ?

Is your query resolved? If so please let us know :)
