### ISSUE TITLE
Got a problem with sprites

### ISSUE THREAD

**Issue by xFreakss** [PokeAPI/sprites#93]
Trying to explain it in a succinct way:

Shiny Galarian Slowking: (10169)
[Official Artwork](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/10169.png)

Galarian Articuno: (10169)
[Official Artwork](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10169.png)

But `25.png` and `/shiny/25.png` are the same pokemon in different forms.

Im going kinda "blind" fetch the shiny form of a random pokemon, some times works well, some times i get a slowking galar lol
in this case i gone for a Shiny Galarian Articuno, which doesn't exists, but it will be hard thing for me to filter in code

**The API does not gives me information about the shiny form on Official Artwork, this would fix my issue!**

note i would get a similar problem if trying to fetch the Galarian Slowking shiny form, because their links are [`10172.png`](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10172.png) and [`shiny/10169.png`](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/10169.png)

**Comment by C-Garza** [comment]
I think I'm confused. Does this happen with all sprites or just these two? It looks like those two just got switched and need to be fixed. `10169` is supposed to be `articuno-galar`, and `10172` is supposed to be `slowking-galar`. 
Or are you looking to extend the `sprites` to have an `official-artwork/shiny` field?

**Comment by xFreakss** [comment]
I presented these 2 cases to illustrate the problem, it seems that the numbering was done based on the images that were available or they're swapped, no clue.

I don't think there is an shiny-articuno-galar on official-artwork, but there is no way for me to know that from the information that is served in the API, I am getting the images of the shiny version by writing the URL, exactly because it is not served by the API.

Yes, I would like to have information about official-artwork/shiny/ in the API

**Comment by C-Garza** [comment]
Yeah, if they're returning different pokemon for the id, then they are the wrong image and should be fixed. `/pokemon/10169` should always be `articuno-galar` and `10172` should always be `slowking-galar`, regardless of shiny or not. 
These official-artwork shiny images are a new addition and haven't been added to the api yet, which is why they don't show up on a `/pokemon/{id}` call. They have to be added to the [`build.py`](https://github.com/PokeAPI/pokeapi/blob/master/data/v2/build.py) file. You're welcome to add a PR to add the field if you'd like, I'm not sure when anyone will get around to doing it. 😄

**Comment by xFreakss** [comment]
How contributions are handled? When his PR will go live?

**Comment by C-Garza** [comment]
We have to wait for the  [api-data](https://github.com/PokeAPI/api-data/pull/124) PR to be merged in.

**Comment by Naramsim** [comment]
sorry!! I merged it!

**Comment by Naramsim** [comment]
in ~1h will be live, will you be able to test it?
