### ISSUE TITLE
can't able to access images in sprites 

### ISSUE THREAD

**Issue by gowthamtn37** [PokeAPI/sprites#95]
its happening for all Pokémon 
https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png

**Comment by DevMike123** [comment]
Can you please explain the problem?

**Comment by gowthamtn37** [comment]
when i try to acess the images in sprites. its not opening.

**Comment by gowthamtn37** [comment]
when i try to acess the images in sprites. its not opening.
